config/routes.rb
Rails.application.routes.draw do
  root 'costumers#index'
  resources :costumers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/costumer.rb
class Costumer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/costumers_controller.rb
class CostumersController < ApplicationController
  before_action :set_costumer, only: [:show, :edit, :update, :destroy]

  # GET /costumers
  # GET /costumers.json
  def index
    @costumers = Costumer.all
  end

  # GET /costumers/1
  # GET /costumers/1.json
  def show
  end

  # GET /costumers/new
  def new
    @costumer = Costumer.new
  end

  # GET /costumers/1/edit
  def edit
  end

  # POST /costumers
  # POST /costumers.json
  def create
    @costumer = Costumer.new(costumer_params)

    respond_to do |format|
      if @costumer.save
        format.html { redirect_to @costumer, notice: 'Costumer was successfully created.' }
        format.json { render :show, status: :created, location: @costumer }
      else
        format.html { render :new }
        format.json { render json: @costumer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costumers/1
  # PATCH/PUT /costumers/1.json
  def update
    respond_to do |format|
      if @costumer.update(costumer_params)
        format.html { redirect_to @costumer, notice: 'Costumer was successfully updated.' }
        format.json { render :show, status: :ok, location: @costumer }
      else
        format.html { render :edit }
        format.json { render json: @costumer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costumers/1
  # DELETE /costumers/1.json
  def destroy
    @costumer.destroy
    respond_to do |format|
      format.html { redirect_to costumers_url, notice: 'Costumer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_costumer
      @costumer = Costumer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def costumer_params
      params.require(:costumer).permit(:name, :last, :customer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/costumers_helper.rb
module CostumersHelper
end

app/views/costumers/_form.html.erb
<%= form_with(model: costumer, local: true) do |form| %>
  <% if costumer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(costumer.errors.count, "error") %> prohibited this costumer from being saved:</h2>

      <ul>
        <% costumer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :last %>
    <%= form.text_field :last %>
  </div>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.number_field :customer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/costumers/edit.html.erb
<h1>Editing Costumer</h1>

<%= render 'form', costumer: @costumer %>

<%= link_to 'Show', @costumer %> |
<%= link_to 'Back', costumers_path %>

app/views/costumers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Costumers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @costumers.each do |costumer| %>
      <tr>
        <td><%= costumer.name %></td>
        <td><%= costumer.last %></td>
        <td><%= costumer.customer_id %></td>
        <td><%= link_to 'Show', costumer %></td>
        <td><%= link_to 'Edit', edit_costumer_path(costumer) %></td>
        <td><%= link_to 'Destroy', costumer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Costumer', new_costumer_path %>

app/views/costumers/new.html.erb
<h1>New Costumer</h1>

<%= render 'form', costumer: @costumer %>

<%= link_to 'Back', costumers_path %>

app/views/costumers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @costumer.name %>
</p>

<p>
  <strong>Last:</strong>
  <%= @costumer.last %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @costumer.customer_id %>
</p>

<%= link_to 'Edit', edit_costumer_path(@costumer) %> |
<%= link_to 'Back', costumers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>